### ISSUE TITLE
Alerts module

### ISSUE THREAD

**Issue by kvokka** [ib-ruby/ib-extensions#1]
Can you please double check the `ib-extensions/lib/alerts/base-alert.rb` file, cos it looks like it should be in api?

Maybe i just misunderstood something. Thank u

**Comment by topofocus** [comment]
You are right and wrong.
If ib-api just provides the api to the ruby world, then it should basically  gather information, ie. account informations, contract infos, scanner data, news and orderstatus. In addition it should send orders, too. 

Any additional stuff should go to other gems. 
IB::Alert  translates Alerts to ruby-classes. It is currently used by gateway and account-infos. 

You are right, its not properly required. 
Perhaps its best, to provide this functionality  as extension as well.

**Comment by kvokka** [comment]
Thank you for such a clear explanation. Will leave it as it is then
